### ISSUE TITLE
Спроектировать схему БД

### ISSUE THREAD

**Issue by a-ovch** [anastasija-stepanova/Servise-PageLoadTest#3]
Спроектировать ER-диаграмму БД сервиса

**Comment by a-ovch** [comment]
Доработать схему с учетом хранения распарсенных данных.

**Comment by a-ovch** [comment]
1. Убрать дублирование данных;
2. Описать таблицы более точно;
3. Добавить первичные ключи;
4. Добавить внешние ключи;
5. Добавить таблицу для хранения полученных данных.

**Comment by anastasija-stepanova** [comment]
![tnzfvq-6cd4](https://user-images.githubusercontent.com/24208124/27957427-2919906e-6327-11e7-9ac4-0fcd202a2ecf.jpg)

**Comment by a-ovch** [comment]
1. Первичные ключи;
2. Показать внешние связи у таблиц;
3. Сделать новую схему, которая будет содержать следующие таблицы: информация о пользователе, "сырые" данные, усредненная статистика по тесту, тест, список url'ов пользователя.

Добавить информацию о ключе API.

**Comment by anastasija-stepanova** [comment]
![0ypviukdvvi](https://user-images.githubusercontent.com/24208124/28016435-fac54ec6-657c-11e7-98bd-7620ff737985.jpg)

**Comment by a-ovch** [comment]
**schema.sql**

1. Добавить проверки на существование базы данных/таблиц, чтобы данный SQL выполнялся даже на созданное базе (см. IF NOT EXISTS);

2. Мне не очень нравится название БД. Слово **testing** как-то сразу воспринимается, будто этот код был именно в целях тестирования приложения разработан;

3. Неправильно написан тип, не нужен пробел после запятой:

`test_id iNT(11) NOT NULL ,`

4. Столбец **test_info.test_url** должен быть внешним ключом соответствующей таблицы - мы же храним эти данные;

5. **test_info.completed** судя по названию поля тут будет хранится простейшее значение 0 или 1. Не много ли для этого INT(11)?

6.  Не очень нравится название таблицы **url_sites**, какое-то масло-масляное. Давай еще подумаем. Также лишний пробел после NULL:

`id INT(11) NOT NULL  AUTO_INCREMENT,`


7. А TINYINT(1) не подходит?

`type_view TINYINT(4) NOT NULL,`

8. Почему столбец **average_result.test_id** имеет тип VARCHAR(255)?
Описание внешнего ключа у других таблиц оформлено иначе:

`FOREIGN KEY (test_id) REFERENCES test_info(id) ON DELETE CASCADE`

**Comment by a-ovch** [comment]
**schema.sql**

1. Назвать БД по названию сервиса;

2. Не исправлено замечание:

> 3. Неправильно написан тип, не нужен пробел после запятой:
> test_id iNT(11) NOT NULL ,

3. Поправить связывание таблицы test_info и site_url. Связывание должно быть по первичному ключу;

4. Для хранения timestamp использовать тип TIMESTAMP;

5. user_urls -> user_url
site_url -> url

6. не исправлено замечание

>Описание внешнего ключа у других таблиц оформлено иначе:
